export enum ETranslateFR {
  REQUIRED_PASSWORD = "Mot de passe requis",
  REQUIRED_EMAIL = "E-mail est requis",
  REQUIRED_LASTNAME = "Nom est requis",
  REQUIRED_FIRSTNAME = "Prénom est requis",
  REQUIRED_ADRESSE = "Adresse est obligatoire",
  REQUIRED_TELEPHONE = "Numéro de téléphone est obligatoire",
  REQUIRED_CODE_AFFILIATION_CNAM = "Le code Affiliation CNAM est obligatoire",
  REQUIRED_MATRICULEFISCALE = "Le matricule fiscal est requis",
  ERROR_REGEX_PASSWORD = "Doit inclure au moins 1 lettre maj et min, 1 chiffre et caractère spécial",
  ERROR_REGEX_EMAIL = "E-mail doit être valide",
  ERROR_REGEX_NAME = "Nom doit être valide",
  ERROR_REGEX_ADRESSE = " Adresse doit être valide",
  ERROR_REGEX_LASTNAME = "Prenom doit être valide",
  ERROR_REGEX_DESCRIPTION = "Description doit être valide",
  CONFIRM_PASSWORD = "Vous devez confirmer votre mot de passe",
  REGEX_CONFIRM_PASSWORD = "Le mot de passe et la confirmation ne correspondent pas",
  ERROR_PHONE_VALIDATION = "Numéro de téléphone invalide!",
  REQUIRED_PHONE = "Numéro de téléphone est obligatoire",
  REQUIRED_SOCIALREASON = "Raison social est obligatoire",
  REQUIRED_EMPLOYEENUMBER ="Nombre des employes est obligatoire",
  ERROR_SELECT_EMPLOYEENUMBERS = "Il faut choisir une seul catégorie",
  REQUIRED = "Champs obligatoire"
}
